# Generated by Django 5.2.3 on 2025-06-12 08:36

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('resume', models.FileField(blank=True, null=True, upload_to='resumes/')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidaterole', to='assessment_app.role')),
            ],
        ),
        migrations.CreateModel(
            name='Evaluator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessment_app.candidate')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evalsect', to='assessment_app.section')),
            ],
            options={
                'unique_together': {('user', 'candidate')},
            },
        ),
        migrations.CreateModel(
            name='SectionWeight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessment_app.role')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weights', to='assessment_app.section')),
            ],
            options={
                'unique_together': {('section', 'weight', 'role')},
            },
        ),
    ]
