# Generated by Django 5.2.3 on 2025-06-12 09:36

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Criteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criteria_title', models.CharField(max_length=100, unique=True)),
                ('criteria_description', models.TextField()),
                ('criteria_weight', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('criteria_score', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('criteria_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criteria', to='assessment_app.section')),
            ],
        ),
    ]
