# Generated by Django 5.2.3 on 2025-06-12 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessment_app', '0002_criteria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='criteria',
            name='criteria_score',
        ),
    ]
