# Generated by Django 5.2.3 on 2025-06-12 10:08

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment_app', '0003_remove_criteria_criteria_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateCriterionScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessment_app.candidate')),
                ('criterion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessment_app.criteria')),
                ('evaluator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessment_app.evaluator')),
            ],
            
        ),
    ]
