# Generated by Django 5.2.1 on 2025-06-12 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessment_app', '0005_alter_candidatecriterionscore_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='candidatecriterionscore',
            unique_together=set(),
        ),
    ]
