# Generated by Django 5.2.1 on 2025-06-12 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessment_app', '0006_alter_candidatecriterionscore_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='candidatecriterionscore',
            unique_together={('criterion', 'score')},
        ),
    ]
