# Generated by Django 5.2.3 on 2025-06-13 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment_app', '0008_alter_candidatecriterionscore_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='criteria',
            name='criteria_title',
            field=models.CharField(max_length=100),
        ),
    ]
