# Generated by Django 5.2.1 on 2025-06-17 10:23

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment_app', '0009_alter_criteria_criteria_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='criteria',
            name='criteria_weight',
        ),
        migrations.AlterUniqueTogether(
            name='sectionweight',
            unique_together={('section', 'role')},
        ),
        migrations.CreateModel(
            name='CriteriaWeight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('criteria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessment_app.criteria')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessment_app.role')),
            ],
        ),
    ]
