# Generated by Django 5.2.1 on 2025-06-17 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessment_app', '0010_remove_criteria_criteria_weight_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sectionweight',
            unique_together={('section', 'role', 'weight')},
        ),
    ]
