# Generated by Django 5.2.1 on 2025-06-17 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment_app', '0011_alter_sectionweight_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatecriterionscore',
            name='is_evaluated',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
