# Generated by Django 5.2.1 on 2025-06-17 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessment_app', '0012_candidatecriterionscore_is_evaluated'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='criteriaweight',
            unique_together={('criteria', 'role', 'weight')},
        ),
    ]
