# Generated by Django 5.2.1 on 2025-06-17 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment_app', '0013_alter_criteriaweight_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatecriterionscore',
            name='criterion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessment_app.criteriaweight'),
        ),
    ]
