# Generated by Django 5.2.1 on 2025-06-17 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessment_app', '0014_alter_candidatecriterionscore_criterion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='evaluator',
            options={'permissions': [('add_candidatecriterionscore', 'Can add Candidate Criterion Score'), ('change_candidatecriterionscore', 'Can change Candidate Criterion Score'), ('delete_candidatecriterionscore', 'Can delete Candidate Criterion Score'), ('view_candidatecriterionscore', 'Can view Candidate Criterion Score'), ('view_candidate', 'Can view Candidate'), ('view_section', 'Can view Section'), ('view_criteria', 'Can view Criteria'), ('view_criteriaweight', 'Can view Criteria Weight'), ('view_sectionweight', 'Can view Section Weight')]},
        ),
    ]
