# Generated by Django 5.2.1 on 2025-06-17 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment_app', '0015_alter_evaluator_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatecriterionscore',
            name='is_evaluated',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
